# LangChain4J Configuration for MicroProfile Config 3.1
# These properties can be overridden by environment variables or system properties

dev.langchain4j.cdi.plugin.customer-support-agent.class=dev.langchain4j.model.openai.OpenAiStreamingChatModel
dev.langchain4j.cdi.plugin.customer-support-agent.config.api-key=${OPENAI_API_KEY}
dev.langchain4j.cdi.plugin.customer-support-agent.config.model-name=gpt-4o
dev.langchain4j.cdi.plugin.customer-support-agent.config.log-requests=true
dev.langchain4j.cdi.plugin.customer-support-agent.config.log-responses=true

dev.langchain4j.cdi.plugin.customer-support-agent.config.temperature=1.0
dev.langchain4j.cdi.plugin.customer-support-agent.config.max-tokens=1000
dev.langchain4j.cdi.plugin.customer-support-agent.config.frequency-penalty=0

#--8<-- [start:rag-retriever]
dev.langchain4j.cdi.plugin.doc-retriever.class=dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever
dev.langchain4j.cdi.plugin.doc-retriever.config.embeddingStore=lookup:@default
dev.langchain4j.cdi.plugin.doc-retriever.config.embeddingModel=lookup:@default
dev.langchain4j.cdi.plugin.doc-retriever.config.maxResults=3
dev.langchain4j.cdi.plugin.doc-retriever.config.minScore=0.75
#--8<-- [end:rag-retriever]

# Location of documents to ingest for RAG
#--8<-- [start:rag-embeddings]
customer-support-agent.rag.docs.dir=rag
customer-support-agent.rag.max-segment-size=100
customer-support-agent.rag.max-overlap-size=25
#--8<-- [end:rag-embeddings]

# If you want to use a different provider or run an LLM on your local machine,
# uncomment this line and update the url/port accordingly.
# dev.langchain4j.cdi.plugin.customer-support-agent.config.base-url=http://localhost:11434/v1

# If your LLM is hosted by a provider/runtime that does not support HTTP 2, such as LMStudio or vLLM, uncomment this
# line and update the url/port accordingly.
# dev.langchain4j.cdi.plugin.customer-support-agent.config.httpClientBuilder=dev.langchain4j.workshop.Http11ClientBuilder