# LangChain4J Configuration for MicroProfile Config 3.1
# These properties can be overridden by environment variables or system properties

dev.langchain4j.cdi.plugin.customer-support-agent.class=dev.langchain4j.model.openai.OpenAiStreamingChatModel
dev.langchain4j.cdi.plugin.customer-support-agent.config.api-key=${OPENAI_API_KEY}
dev.langchain4j.cdi.plugin.customer-support-agent.config.model-name=gpt-4o
dev.langchain4j.cdi.plugin.customer-support-agent.config.log-requests=true
dev.langchain4j.cdi.plugin.customer-support-agent.config.log-responses=true

dev.langchain4j.cdi.plugin.customer-support-agent.config.temperature=0.0
dev.langchain4j.cdi.plugin.customer-support-agent.config.max-tokens=2000
dev.langchain4j.cdi.plugin.customer-support-agent.config.frequency-penalty=0

dev.langchain4j.cdi.plugin.customer-support-agent-memory.class=dev.langchain4j.memory.chat.MessageWindowChatMemory
dev.langchain4j.cdi.plugin.customer-support-agent-memory.scope=jakarta.enterprise.context.ApplicationScoped
dev.langchain4j.cdi.plugin.customer-support-agent-memory.config.maxMessages=20

dev.langchain4j.cdi.plugin.doc-retriever.class=dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever
dev.langchain4j.cdi.plugin.doc-retriever.config.embeddingStore=lookup:@default
dev.langchain4j.cdi.plugin.doc-retriever.config.embeddingModel=lookup:@default
dev.langchain4j.cdi.plugin.doc-retriever.config.maxResults=3
dev.langchain4j.cdi.plugin.doc-retriever.config.minScore=0.6

# Location of documents to ingest for RAG
customer-support-agent.rag.docs.dir=rag
customer-support-agent.rag.max-segment-size=100
customer-support-agent.rag.max-overlap-size=25

vector.store.hostname=localhost
vector.store.port=5432
vector.store.database=postgres
vector.store.username=postgres
vector.store.password=password
vector.store.dimension=384

dev.langchain4j.cdi.plugin.streamablehttptransport.class=dev.langchain4j.mcp.client.transport.http.StreamableHttpMcpTransport
dev.langchain4j.cdi.plugin.streamablehttptransport.config.url=http://localhost:9081/mcp
dev.langchain4j.cdi.plugin.streamablehttptransport.config.logRequests=true
dev.langchain4j.cdi.plugin.streamablehttptransport.config.logResponses=true

dev.langchain4j.cdi.plugin.mcpclient.class=dev.langchain4j.mcp.client.DefaultMcpClient
dev.langchain4j.cdi.plugin.mcpclient.config.transport=lookup:@streamablehttptransport

dev.langchain4j.cdi.plugin.mcp.class=dev.langchain4j.mcp.McpToolProvider
dev.langchain4j.cdi.plugin.mcp.config.mcpClients=lookup:@mcpclient

# If you want to use a different provider or run an LLM on your local machine,
# uncomment this line and update the url/port accordingly.
# dev.langchain4j.cdi.plugin.customer-support-agent.config.base-url=http://localhost:11434/v1

# If your LLM is hosted by a provider/runtime that does not support HTTP 2, such as LMStudio or vLLM, uncomment this
# line and update the url/port accordingly.
# dev.langchain4j.cdi.plugin.customer-support-agent.config.httpClientBuilder=dev.langchain4j.workshop.Http11ClientBuilder